#!/bin/sh

# Create the experiment user if does not exist already.
# User could already exist if this is an upgrade instead of a fresh installation.
if ! (id -u exp253 >/dev/null 2>&1); then
  useradd exp253 -m -d /home/exp253 -s /bin/sh
  passwd -l exp253
fi
